# Use old trusty image since new one breaks our builds
# See: https://blog.travis-ci.com/2017-12-12-new-trusty-images-q4-launch
#group: deprecated-2017Q4

os:
  - linux
  - osx

# Supported osx/xcode versions: https://docs.travis-ci.com/user/languages/objective-c/#Supported-Xcode-versions
# See also: https://blog.travis-ci.com/2016-10-04-osx-73-default-image-live/
osx_image: xcode9.4
addons:
  homebrew:
    casks:
    - basictex
#    packages:
#    - doxygen
    update: true

#cache:
#  directories:
#    # Disabled homebrew cache, did not appear to do anything
#    #- $HOME/Library/Caches/Homebrew
#    - $HOME/nvidia_cache
#  # https://docs.travis-ci.com/user/caching/#Setting-the-timeout
#  timeout: 540  # seconds: 9 min cache upload time (default is 3 min)

language: c
sudo: required

services:
  - docker

env:
  global:
    secure:
     - "aOY6RAOmqJ/hWDzN1YCTlbwA/SMiGPJpLGfPrV0CWn74WbRlkpWL/m39T2QjI8Dd7AV7AtzqCw3lXlECNEE8kriA7VIPlHe3O712yAU8t0xftqqiLJzbkR+3qzhQD8z8surkLrr1yfBfVXYarDgiGqSKtngA3hzfwupSRBmu27FvuL9t3GpPHZgJhtx5oIQjelNLMJYFWG4Ev8RhglYTknRW2HAYVZVQKaahS4xQMOrjnoWKekY02ya3KMLa0+R5i+kfSVTuqWIU0HT7UEsYxBPZi332we6VWuNZZIhk8rKPkBRLmcGAfQm54WRNLKSJ8oWtYgikMRHs2S9lDxkpMfkP5DudLe8wR65dST5aqlGGKWXOXFvmxNr3ZZJ7HLnKJX4et02t2fDvG+nb2Ai2JkQUAI5/MOqKHY1vivj7VskW5WIJjGqPYcXhygnPnUtG6tbxD1oN1LXReWLY0EEEMOxRg8rhfkNBkmgCripMkmsltRknFl3LuJRdLsdQoXIpUGqL61uHLbme57wWiJLqp9PCwl8+4gWq1iPdKbO5xsk/jzpknwWy8FbdirXa/rpJM59jPQk9gnogXzxjKF8DCddYKtQ9Knz1r2VoKZAbywFtyjNe81qXmhnnwg6B4Ln+sk7iVXiReD47F0o/8ezkTh6eL1UWLSALpLz4m3r16Q8="
  jobs:
    - CUDA_VERSION="7.5" CUDA_SHORT_VERSION="75"
    - CUDA_VERSION="8.0" CUDA_SHORT_VERSION="80"
    - CUDA_VERSION="9.0" CUDA_SHORT_VERSION="90"
    - CUDA_VERSION="9.1" CUDA_SHORT_VERSION="91"
    - CUDA_VERSION="9.2" CUDA_SHORT_VERSION="92"
    - CUDA_VERSION="10.0" CUDA_SHORT_VERSION="100"
    - CUDA_VERSION="10.1" CUDA_SHORT_VERSION="101"


install:
  - export DOCKER_IMAGE="jchodera/omnia-linux-anvil:texlive18-cuda${CUDA_SHORT_VERSION}"
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      docker pull ${DOCKER_IMAGE};
    fi

script:
  # Retrieve conda-build-all
  # DEBUG: Temporarily commented out to test
  #- wget -O conda-build-all --quiet https://raw.githubusercontent.com/omnia-md/conda-recipes/master/conda-build-all
  - chmod +x conda-build-all
  # Select upload destination
  - export CHECK_AGAINST="--check-against omnia --check-against omnia/label/cuda${CUDA_SHORT_VERSION}"
  - export CHECK_AGAINST="$CHECK_AGAINST --check-against omnia/label/rc --check-against omnia/label/rccuda${CUDA_SHORT_VERSION}"
  - export CHECK_AGAINST="$CHECK_AGAINST --check-against omnia/label/beta --check-against omnia/label/betacuda${CUDA_SHORT_VERSION}"
  - if [[ "${TRAVIS_PULL_REQUEST}" == "false" && "${TRAVIS_BRANCH}" == "master" ]]; then
        export UPLOAD="$CHECK_AGAINST --upload omnia";
    else
        export UPLOAD="$CHECK_AGAINST";
    fi
  - echo $UPLOAD
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then

        docker run -e UPLOAD -e BINSTAR_TOKEN -e CUDA_VERSION -e CUDA_SHORT_VERSION -e TRAVIS_PULL_REQUEST
            -t -i --rm -v `pwd`:/io ${DOCKER_IMAGE}
            bash /io/devtools/docker-build.sh;

    elif [[ "$TRAVIS_OS_NAME" == "osx" ]]; then

        echo "Building osx...";
        export NVIDIA_CACHE=$HOME/nvidia_cache;
        bash devtools/osx-build.sh;

    fi
